version: '3'
services:
  vets-website:
    platform: linux/amd64
    image: vets-website:${IMAGE_TAG:-latest}
    build:
      context: .
      additional_contexts:
        - content-build-context=../content-build
        - vagov-content-context=../vagov-content
    environment:
      WEB_HOST: 'vets-website'
      WEB_PORT: 3001
      API_HOST: 'vets-website'
    ports:
      - "3001:3001"
      - "3000:3000"
      - "9515:9515"
    command: ./script/run-spruce-application.sh
    ipc: host
    networks:
      - default
    
